import { v4 as uuid } from "uuid";
import { formatDate } from "../utils/authUtils";
/**
 * User Database can be added here.
 * You can add default users of your wish with different attributes
 * */

export const users = [

  {
    _id: uuid(),
    firstName: "Sagar",
    lastName: "Shah",
    username: "sagar@gmail.com",
    password: "sagar123",
    userHandler: "sagar98",
    bio: "Passionate about entrepreneurship",
    link: "https://peerlist.io/sagar98",
    profilePic: "https://example.com/profilepics/sagar.jpg",
    createdAt: formatDate(),
    updatedAt: formatDate(),
  },
  {
    _id: uuid(),
    firstName: "Henry",
    lastName: "Smith",
    username: "henry@example.com",
    password: "henry123",
    userHandler: "henrysmith",
    bio: "Marketing professional with a creative edge",
    link: "https://peerlist.io/henrysmith",
    profilePic: "https://example.com/profilepics/henry.jpg",
    createdAt: formatDate(),
    updatedAt: formatDate(),
  },
  {
    _id: uuid(),
    firstName: "Alice",
    lastName: "Johnson",
    username: "alice@example.com",
    password: "alice123",
    userHandler: "alicejohnson",
    bio: "Passionate about creating meaningful user experiences",
    link: "https://peerlist.io/alicejohnson",
    profilePic: "https://example.com/profilepics/alice.jpg",
    createdAt: formatDate(),
    updatedAt: formatDate(),
  },
  {
    _id: uuid(),
    firstName: "Bob",
    lastName: "Davis",
    username: "bob@example.com",
    password: "bob123",
    userHandler: "bobdavis",
    bio: "Tech geek and problem solver",
    link: "https://peerlist.io/bobdavis",
    profilePic: "https://example.com/profilepics/bob.jpg",
    createdAt: formatDate(),
    updatedAt: formatDate(),
  },
  {
    _id: uuid(),
    firstName: "Charlie",
    lastName: "Wilson",
    username: "charlie@example.com",
    password: "charlie123",
    userHandler: "charliewilson",
    bio: "Business strategist and entrepreneur",
    link: "https://peerlist.io/charliewilson",
    profilePic: "https://example.com/profilepics/charlie.jpg",
    createdAt: formatDate(),
    updatedAt: formatDate(),
  },
  {
    _id: uuid(),
    firstName: "Grace",
    lastName: "Miller",
    username: "grace@example.com",
    password: "grace123",
    userHandler: "gracemiller",
    bio: "HR professional with a passion for employee well-being",
    link: "https://peerlist.io/gracemiller",
    profilePic: "https://example.com/profilepics/grace.jpg",
    createdAt: formatDate(),
    updatedAt: formatDate(),
  },
  {
    _id: uuid(),
    firstName: "Emma",
    lastName: "Thomas",
    username: "emma@example.com",
    password: "emma123",
    userHandler: "emmathomas",
    bio: "Creative designer with a passion for aesthetics",
    link: "https://peerlist.io/emmathomas",
    profilePic: "https://example.com/profilepics/emma.jpg",
    createdAt: formatDate(),
    updatedAt: formatDate(),
  },
  {
    _id: uuid(),
    firstName: "David",
    lastName: "Taylor",
    username: "david@example.com",
    password: "david123",
    userHandler: "davidtaylor",
    bio: "Finance professional with a knack for numbers",
    link: "https://peerlist.io/davidtaylor",
    profilePic: "https://example.com/profilepics/david.jpg",
    createdAt: formatDate(),
    updatedAt: formatDate(),
  },
  {
    _id: uuid(),
    firstName: "Frank",
    lastName: "Brown",
    username: "frank@example.com",
    password: "frank123",
    userHandler: "frankbrown",
    bio: "Entrepreneur and startup enthusiast",
    link: "https://peerlist.io/frankbrown",
    profilePic: "https://example.com/profilepics/frank.jpg",
    createdAt: formatDate(),
    updatedAt: formatDate(),
  },
];
